<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="src\settings.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="src\settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
	  <None Update="src\planetsExtended.csv">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="src\planetsExtended.xml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
  </ItemGroup>

</Project>
